
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * After the user successfully logged in, the user-profile should be displayed with 
 * the registered information such as user name, first name, last name and email. 
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
        show_profile();
    }
    /**
     * This method gets all user-data from database and displays them in related jTextFields
     */
    private void show_profile() {
        Connection connection = DBconnection.connectToDatabase();
        try {
                int id = ICalendarFrame.user_id;
                PreparedStatement pstmt = (PreparedStatement)
                connection.prepareStatement("select fname, lname, email, uname from users where ID = ?");
                pstmt.setInt(1,id);
                
                ResultSet rs= pstmt.executeQuery();
                
                while(rs.next()){
                    
                    String uname = rs.getString("uname");
                    jlUserName.setText(uname);
                    String fname = rs.getString("fname");
                    jtxtFirstName.setText(fname);   
                    String lname = rs.getString("lname");
                    jtxtLastName.setText(lname); 
                    String email = rs.getString("email");
                    jtxtEmail.setText(email); 
                }
            connection.close();    
            } catch (SQLException ex) {
            Logger.getLogger(ICalendarFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnMyCalendar = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();
        jlPassword = new javax.swing.JPanel();
        jlFirstName = new javax.swing.JLabel();
        jlLastName = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtLastName = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jbtnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlUserName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");

        jPanel1.setBackground(new java.awt.Color(250, 228, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 204), 4));
        jPanel1.setForeground(new java.awt.Color(250, 228, 250));

        jPanel2.setBackground(new java.awt.Color(250, 228, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 204), 4));

        jbtnMyCalendar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnMyCalendar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnMyCalendar.setText("My Calendar");
        jbtnMyCalendar.setBorderPainted(false);
        jbtnMyCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMyCalendarActionPerformed(evt);
            }
        });

        jbtnLogout.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLogout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnLogout.setText("Logout");
        jbtnLogout.setBorderPainted(false);
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jbtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnMyCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbtnMyCalendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLogout)
                .addContainerGap())
        );

        jlPassword.setBackground(new java.awt.Color(250, 228, 250));
        jlPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 4));

        jlFirstName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlFirstName.setText("Firstname");

        jlLastName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlLastName.setText("Lastname");

        jlEmail.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlEmail.setText("Email");

        jtxtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstNameActionPerformed(evt);
            }
        });

        jbtnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jbtnUpdate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.setBorderPainted(false);
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jlPasswordLayout = new javax.swing.GroupLayout(jlPassword);
        jlPassword.setLayout(jlPasswordLayout);
        jlPasswordLayout.setHorizontalGroup(
            jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlPasswordLayout.createSequentialGroup()
                        .addGroup(jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jtxtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFirstName, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jlPasswordLayout.setVerticalGroup(
            jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlPasswordLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlFirstName)
                    .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlLastName)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlEmail)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jbtnUpdate)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(250, 228, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 204), 4));

        jlUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo_2021-01-26_00-20-25.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtFirstNameActionPerformed
/**
 * If you want to add an event or check the Calendar, you should press MyCalendar button
 * @param evt Event listener
 */
    private void jbtnMyCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMyCalendarActionPerformed
        // TODO add your handling code here
        
        dispose();        
        CalendarPage call = new CalendarPage();
        call.setVisible(true);
    }//GEN-LAST:event_jbtnMyCalendarActionPerformed
/**
 * If user wants to edit his/her data, he/she should change the data in jTextFields and then press the update button
 * to save changes
 * @param evt Event listener
 */
    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Update");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Update", "Confirm Update", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            
        
        Connection connection = DBconnection.connectToDatabase();

        if(connection != null){
            try {

                int id = ICalendarFrame.user_id;
                String Firstname = jtxtFirstName.getText();
                String Lastname = jtxtLastName.getText();
                String Email = jtxtEmail.getText();
               
                
                
                PreparedStatement update = connection.prepareStatement("update users set fname = ?,lname = ?,email = ? where id = ?");

                update.setString(1,Firstname);
                update.setString(2,Lastname);
                update.setString(3,Email);
                update.setInt(4,id);

                int i= update.executeUpdate();

                if(i >=1){
                    
                    JOptionPane.showMessageDialog(null,"Information has been Updated!");

                    show_profile(); // show after updating.
                   

                }else{
                    JOptionPane.showMessageDialog(null,"Update failed!");
                }
             connection.close();
            } catch (SQLException ex){
                Logger.getLogger(ICalendarFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("NO DATABASE CONNECTION!");
        }
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed
/**
 *  If user presses the logout button, ICalenderFrame will be opened
 * @param evt Event listener
 */
    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ICalendarFrame cal = new ICalendarFrame();
        cal.setVisible(true);
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnMyCalendar;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFirstName;
    private javax.swing.JLabel jlLastName;
    private javax.swing.JPanel jlPassword;
    private javax.swing.JLabel jlUserName;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    // End of variables declaration//GEN-END:variables
}
